(if (<= emacs-major-version 26)
    (package-initialize)
  (package-refresh-contents))
(setq enable-local-eval nil
      enable-local-variables nil)
(let ((elc-loc "~/Dotfiles/.emacs.d/config.elc")
      (org-loc "~/Dotfiles/.emacs.d/config.org"))
  (when (not (file-exists-p elc-loc))
    (org-babel-load-file org-loc t))
  (let* ((org-time (time-convert (file-attribute-modification-time (file-attributes org-loc)) 'integer))
         (elc-time (time-convert (file-attribute-modification-time (file-attributes elc-loc)) 'integer)))
    (if (> org-time (+ 20 elc-time))
        (org-babel-load-file org-loc t)
      (load-file elc-loc))))
