(require 'package)
(setq package-enable-at-startup nil)

(setq package-archives
      '(("elpa"     . "https://elpa.gnu.org/packages/")
        ("melpa"        . "https://melpa.org/packages/"))
      package-archive-priorities
      '(("elpa"     . 5)
        ("melpa"        . 10)))

(package-initialize)

;; Bootstrap `use-package`
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
;; Option for usepackage to default to ensure t
(setq use-package-always-ensure t)
;; Follow symlinks instead of asking to follow symlinks
(setq vc-follow-symlinks t)

;; Some visual defaults you can change that i think look ugly af
(setq inhibit-startup-screen t
      initial-buffer-choice 'eshell)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(display-battery-mode)
;; Relative Line numbers r lit
(display-time)
(global-display-line-numbers-mode)
(setq-default display-line-numbers-type 'relative
	      display-line-numbers-current-absolute t
	      display-line-numbers-width 4
	      display-line-numbers-widen t)

;; Easy way to install directly from github using quelpa. Note that this is only used in the config
;; So if you never use it you can just get rid of it
(use-package quelpa
	     :init '(setq quelpa-upgrade-p t
			  quelpa-stable-p t))
;; Add a use-package thing for quelpa
(use-package quelpa-use-package)

;; Add which-key (makes keybinds show all possible things) VERY nice to learn emacs with
(use-package which-key
	     :config (which-key-mode))

;; Adds fuzzy things for many emacs things
(use-package helm
	     :config
	     (helm-autoresize-mode t)
	     (setq helm-autoresize-max-height 30)
	     (setq helm-display-header-line nil)
	     (define-key helm-map (kbd "TAB") 'helm-execute-persistent-action)
	     (helm-mode t))

;; rebinds M-x to helm for fuzzy matching
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
;; Anything past here is autogenerated every time you run emacs. it is safe to delete this only if you do not use M-x package-install RET and use
;; the actual config instead

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (helm which-key quelpa-use-package quelpa use-package))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
